[[redirects]]
  from = "https://app.graphviser.app/*"
  to = "https://graphviser.app/app/:splat"
  status = 200
  force = true
  
  [[redirects]]
  from = "https://learn.graphviser.app/*"
  to = "https://graphviser.app/learn/:splat"
  status = 200
  force = true
  
  [[redirects]]
  from = "https://docs.graphviser.app/*"
  to = "https://graphviser.app/docs/:splat"
  status = 200
  force = true
